DOMO24-34 Nouvelle activité pour gérer les couleurs des LEDs
btssn-lasalle-84/domotifications-2024 pull request #27
Opened 2024-05-29 20:13 UTC by OthmanLatyaoui

2024-05-29 21:03 UTC, tvaira requested changes

2024-05-29 21:03 UTC, tvaira commented on domotifications-android/Domotifications/app/src/main/java/com/lasalle/domotifications/SelecteurCouleur.java
> +                    //@todo Faire le lien entre la couleur de la LED et de la sélection
Vue en cours :

```java
Log.d(TAG, "pixel = " + pixel);

// Extraction des composantes RGB
int rouge = (pixel >> 16) & 0xff;
int vert = (pixel >> 8) & 0xff;
int bleu = (pixel) & 0xff;
Log.d(TAG, "rouge = " + rouge + " - " + "vert = " + vert + " - " + " bleu = " + bleu);
Log.d(TAG, "rouge = " + String.format("%02X", rouge) + " - " + "vert = " + String.format("%02X", vert) + " - " + " bleu = " + String.format("%02X", bleu));
// ou
int red = Color.red(pixel);
int green = Color.green(pixel);
int blue = Color.blue(pixel);
Log.d(TAG, "rouge = " + red + " - " + "vert = " + green + " - " + " bleu = " + blue);
Log.d(TAG, "rouge = " + String.format("%02X", red) + " - " + "vert = " + String.format("%02X", green) + " - " + " bleu = " + String.format("%02X", blue));

// Conversion au format #RRGGBB
String couleurHTML = String.format("#%06X", (pixel & 0x00FFFFFF));
Log.d(TAG, "couleurHTML = " + couleurHTML);

// Vérification
int couleurRGB =	Color.parseColor(couleurHTML);
Log.d(TAG, "couleurRGB = " + couleurRGB);
```

2024-05-29 21:03 UTC, tvaira commented on domotifications-android/Domotifications/app/src/main/java/com/lasalle/domotifications/FenetreMachine.java
> +        startActivity(new Intent(this, SelecteurCouleur.class));
Oh ! J'imagine que c'est un test mais je n'aime pas du tout ça. Cela ne sert à rien et c'est une très mauvaise habitude. Essaye toujours d'"écrire du code" pour qu'il reste.

2024-05-30 14:08 UTC, OthmanLatyaoui commented
Je ne comprends pas pourquoi je ne peux pas manipuler des layout "comme d'habitude", càd que je ne peux pas mettre une image / un texte n'importe où, et si je rentre une image cela décale toutes les autres images du linear layout en question. Comment cela fonctionne ?

2024-05-30 14:10 UTC, OthmanLatyaoui commented
Aussi pour le color picker en forme de barre je rencontre des difficultés, je n'ai que le cercle

2024-05-30 20:36 UTC, tvaira commented
> Je ne comprends pas pourquoi je ne peux pas manipuler des layout "comme d'habitude", càd que je ne peux pas mettre une image / un texte n'importe où, et si je rentre une image cela décale toutes les autres images du linear layout en question. Comment cela fonctionne ?

Déjà tu n'es pas dans le bon _layout_ ! Le _layout_ `activity_menu_machine.xml` doit contenir en dessous de chaque module une icône "palette" pour permettre à l'utilisateur de cliquer dessus afin de démarrer ton activité `SelecteurCouleur`.

Le clic doit demarrer `SelecteurCouleur` en lui passant le nom du module et sa couleur. Pour cela, on va ajouter des données à l'`Intent` :

```java
Intent intent = new Intent(FenetreMachine.this, SelecteurCouleur.class);
// @todo même chose pour le nom du module
intent.putExtra("couleur", modulesMachines.get(0).getCouleur());
startActivityForResult(intent, CHANGEMENT_COULEUR);
```

`CHANGEMENT_COULEUR` est un code (arbitraire) utilisé pour identifier ensuite la réponse de l'activité.

C'est une constante de la classe : `public static final int CHANGEMENT_COULEUR    = 1;`

Attention !!! Ta classe `Module` est incomplète : elle initialise pas l'attribut couleur dans le constructeur. Ton accesseur `getCouleur()` a été déclaré en `protected` !!!

Dans ton activité `SelecteurCouleur`, il te faut récupérer les données dans la méthode `onCreate()` :

```java
// @todo même chose pour le nom du module
couleurModule = (String)getIntent().getStringExtra("couleur");
Log.d(TAG, "onCreate() couleurModule = " + couleurModule);
```

Tu affectes ensuite le nom et la couleur à tes _widgets_ `TextView` `informationsModule` et `couleurActuelle`.

Ensuite, il te faut gérer tes deux boutons Valider et Annuler de ton activité `SelecteurCouleur` car ils doivent retourner à l'activité précédente.

Le bouton Valider doit lui retourner des données (la nouvelle couleur sélectionnée), pour cela il utilise un `Intent` : 

```java
Intent intent = new Intent();
intent.putExtra("couleur", couleurHTML);
setResult(RESULT_OK, intent);
finish();
```

Le bouton Annuler lui termine simplement l'activité : 

```java
setResult(RESULT_CANCELED);
finish();
```

Maintenant, il te faut récupérer le retour de l'activité. L'activité qui a lancé l'autre activité avec `startActivityForResult()` doit redéfinir une méthode nommée `onActivityResult()` pour gérer le retour : 

```java
protected void onActivityResult(int requestCode, int resultCode, Intent data)
{
    super.onActivityResult(requestCode, resultCode, data);
    Log.d(TAG,
          "onActivityResult() requestCode : " + requestCode + " - resultCode : " + resultCode);
    if(requestCode == CHANGEMENT_COULEUR)
    {
        if(resultCode == RESULT_OK)
        {
            if(data != null)
            {
                String couleurModule = data.getStringExtra("couleur");
                Log.d(TAG, "onActivityResult() couleurModule = " + couleurModule);
                // @todo émettre une requête PATCH pour changer la couleur
            }
        }
    }
}
```

On voit qu'il faut avoir l'id du module pour émettre la requête PATCH pour changer la couleur. Tu as deux solutions pour cela :

1. tu conserves l'id du module "cliqué" dans un attribut
2. tu passes l'id du module "cliqué" dans l'`Intent` à l'aller et au retour (`getIntExtra()`)

2024-05-31 13:12 UTC, tvaira requested changes
Il y a le TODO pour émettre une requête PATCH à faire

2024-05-31 13:12 UTC, tvaira commented on domotifications-android/Domotifications/app/src/main/java/com/lasalle/domotifications/FenetreMachine.java
> +    public static Vector<Module> modulesMachines;    //!< Conteneur des modules machines
Je ne vais pas autoriser cela !!! Pourquoi tu ne me demandes pas avant ?

2024-05-31 13:12 UTC, tvaira commented on domotifications-android/Domotifications/app/src/main/java/com/lasalle/domotifications/FenetreMachine.java
> +        imageSelecteur[1] = (ImageView)findViewById(R.id.couleurMachine1);
Il y en a 3 autres !

2024-05-31 13:12 UTC, tvaira commented on domotifications-android/Domotifications/app/src/main/java/com/lasalle/domotifications/FenetreMachine.java
> +                    startActivity(intent);
Je t'ai dit d'utiliser `startActivityForResult()` !

2024-05-31 13:12 UTC, tvaira commented on domotifications-android/Domotifications/app/src/main/java/com/lasalle/domotifications/Module.java
> +    public String getCouleur()
Tu as vu que l'attribut `couleur` n'est pas initialisé dans le constructeur !  Il sera donc `null` tant que tu ne le fais pas. Il te faudra aussi modifier la base de données pour y intégrer le champ "couleur" pour les modules.

2024-05-31 13:12 UTC, tvaira commented on domotifications-android/Domotifications/app/src/main/java/com/lasalle/domotifications/FenetreMachine.java
> +                    intent.putExtra("idMachine", idMachine);
La classe `SelecteurCouleur` doit fonctionner pour les trois types de modules. Il te faut donc le nommer `idModule` sinon elle ne pourra pas deviner le type !

2024-05-31 13:12 UTC, tvaira commented on domotifications-android/Domotifications/app/src/main/java/com/lasalle/domotifications/SelecteurCouleur.java
> +    protected void onActivityResult(int requestCode, int resultCode, Intent data)
Mais non ! Tu n'as pas compris le principe de fonctionnement. C'est l'activité qui a lancé celle-ci qui attend le résultat de son exécution. En résumé, l'activité qui fait le `startActivityForResult()` doit faire le `onActivityResult()`.  

Cela va t'arranger car cette activité "sait" déjà émettre une requête HTTP !

2024-05-31 13:12 UTC, tvaira commented on domotifications-android/Domotifications/app/src/main/java/com/lasalle/domotifications/SelecteurCouleur.java
> +    private void initialiserHandler() {
Non inutile !

2024-05-31 13:12 UTC, tvaira commented on domotifications-android/Domotifications/app/src/main/java/com/lasalle/domotifications/SelecteurCouleur.java
> +    private void traiterReponsePATCH(String reponse) {
Non inutile !

2024-05-31 13:12 UTC, tvaira commented on domotifications-android/Domotifications/app/src/main/java/com/lasalle/domotifications/SelecteurCouleur.java
> +    private void afficherErreur(String message) {
Non inutile !

2024-05-31 13:12 UTC, tvaira commented on domotifications-android/Domotifications/app/src/main/java/com/lasalle/domotifications/SelecteurCouleur.java
> +        initialiserHandler();
Non !

Par contre, le reste du code est "pourri" par rapport à ce que tu as fait dans les autres activités !!!

2024-06-01 17:10 UTC, tvaira requested changes

2024-06-01 17:10 UTC, tvaira commented on domotifications-android/Domotifications/app/src/main/java/com/lasalle/domotifications/BaseDeDonnees.java
> +          "INSERT INTO modules (id, nom, idTypesModules, actif, couleur, idDomotifications) VALUES (1, 'boîte aux lettres', 1, 1, 'rouge', 1);");
'rouge ' c'est `#FF0000` ! Il te faut mettre des couleurs HTML !!! Reste concentré sur ton travail.

2024-06-02 05:19 UTC, tvaira commented
Renommage de `SelecteurCouleur` en `ParametresModule`  pour gérer aussi le changement de nom du module. Il faut appliquer les changements aux trois types de module.

2024-06-02 06:28 UTC, OthmanLatyaoui commented
Excusez moi je n'ai pas fais exprès pour le "remaniage de code" (les lignes changées qui n'ont rien à voir avec la méthode) automatique avec Android Studio. Je vais faire attention la prochaine fois

2024-06-02 06:31 UTC, OthmanLatyaoui commented
Excusez moi je n'ai pas fais exprès pour les lignes changées qui n'ont rien à voir avec la méthode que j'ai faite ! Je ne sais pas comment enlever ce "remaniement" automatique, j'ai la mauvaise habitude de faire un CTRL + S à chaque fois que je fais quelque chose et ça me fait changer toutes les accolades et espaces !

2024-06-02 07:03 UTC, tvaira commented
> Excusez moi je n'ai pas fais exprès pour les lignes changées qui n'ont rien à voir avec la méthode que j'ai faite ! Je ne sais pas comment enlever ce "remaniement" automatique, j'ai la mauvaise habitude de faire un CTRL + S à chaque fois que je fais quelque chose et ça me fait changer toutes les accolades et espaces !

Dans `Settings →Keymap`, tu sélectionnes `External Tools` et tu affectes un raccourci à `clang-format`. Tu choisis si tu choisis un nouveau comme `Ctrl+MAJ+s`  ou si tu changes `Ctrl+s`

2024-06-02 07:14 UTC, tvaira requested changes
Il te faut :

- modifier tes trois layouts pour avoir l'icone parametres
- renommer `imagesSelecteurCouleur` en `imagesParametres`
- le faire pour les trois classes Fenetre

2024-06-02 07:14 UTC, tvaira commented on domotifications-android/Domotifications/app/src/main/java/com/lasalle/domotifications/BaseDeDonnees.java
> +        db.update("modules", values, "idModule = ?", new String[]{String.valueOf(idModule)});
Tu as déjà trois méthodes "mettreAJour" et là, tu m'inventes quelque chose qui ne fonctionne pas ! Bravo. Je n'arrive pas à comprendre votre façon de travailler. Pour la n-ième fois, je te rappelle que l'`id` n'est pas une clé primaire des modules. Il faut l'id et le type de module.

2024-06-02 07:14 UTC, tvaira commented on domotifications-android/Domotifications/app/src/main/java/com/lasalle/domotifications/FenetreBoiteAuxLettres.java
> +                        for (int i = 0; i < modulesBoitesAuxLettres.size(); ++i)
Non il y a plus simple. Inutile de faire une boucle. Tu récupères le module à partir du `Vector`.

2024-06-02 10:55 UTC, tvaira approved these changes

2024-06-02 11:04 UTC, merged