DOMO24-35 Ajouter et supprimer un module
btssn-lasalle-84/domotifications-2024 pull request #29
Opened 2024-06-04 21:10 UTC by OthmanLatyaoui

2024-06-04 21:10 UTC, OthmanLatyaoui commented
A compléter

2024-06-05 03:48 UTC, tvaira requested changes

2024-06-05 03:48 UTC, tvaira commented on domotifications-android/Domotifications/app/src/main/java/com/lasalle/domotifications/BaseDeDonnees.java
> +                       "idDomotifications) VALUES (1, 'boîte aux lettres 1', 1, 1, '#FF0000', 1);");
Non !!! Cette méthode n'existe pas en réalité. 

Elle permet deux choses : l'utiliser pendant la phase de développement et lors de la démonstration.

Elle permet de démarrer l'application avec déjà une configuration de base "classique" : 5 poubelles, 2 machines et 1 boîte aux lettres.

Il est hors de question d'y ajouter tous les modules possibles !

2024-06-05 03:48 UTC, tvaira commented on domotifications-android/Domotifications/app/src/main/java/com/lasalle/domotifications/BaseDeDonnees.java
> +
C'est quoi ces lignes vides ????????????????!!!!!!!!!!!!!!!!!!!!!!

2024-06-05 03:48 UTC, tvaira commented on domotifications-android/Domotifications/app/src/main/java/com/lasalle/domotifications/Communication.java
> +    public static final String  ADRESSE_IP_STATION = "192.168.1.47"; // Simulateur station
Attention !

2024-06-05 03:48 UTC, tvaira commented on domotifications-android/Domotifications/app/src/main/res/layout/activity_menu_boite_aux_lettres.xml
> +    <LinearLayout
Non ! Le placement de ces deux boutons ne convient pas !

Le bouton supprimer doit se placer dessous le bouton paramètres pour chaque module. Je te rappelle que les actions de suppression doivent toujours être confirmées par l'utilisateur dans une boîte de dialogue.

Le bouton ajouter doit normalement "flotter" en bas à droite. Ici, le plus simple est de l'aligner àdroite avec le bouton accueil.

2024-06-05 13:38 UTC, OthmanLatyaoui commented
Sur le dernier commit : 

- Ajout de la classe BoiteDeDialogue.java
- Ajout de la méthode afficherBoiteDialogueSuppression dans les différentes fenêtres
- Ajout de code dans la méthode initialiserGUI() 

Défauts constatés et à corriger : 

- Lorsqu'on supprime/cache un module et qu'on relance l'activité Fenetre en question, les modules supprimés redeviennent visibles

- Crash de la FenetreBoite pour la raison suivante : 

```bash
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lasalle.domotifications/com.lasalle.domotifications.FenetreBoiteAuxLettres}: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
 Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
at com.lasalle.domotifications.FenetreBoiteAuxLettres.initialiserGUI(FenetreBoiteAuxLettres.java:137)
at com.lasalle.domotifications.FenetreBoiteAuxLettres.onCreate(FenetreBoiteAuxLettres.java:98)
```

- Le code pour ajouter/rendre visible les modules dans la méthode initialiserGUI() ne fonctionne pas 

- Lorsqu'on appuie sur le boutonAjouterModule, seul les modules présents dans la BDD s'affichent

2024-06-05 20:48 UTC, tvaira commented
> Sur le dernier commit :
> 
> * Remaniement de BaseDeDonnees.java avec clangformat
> * Ajout de la classe BoiteDeDialogue.java
> * Ajout de la méthode afficherBoiteDialogueSuppression dans les différentes fenêtres
> * Ajout de code dans la méthode initialiserGUI()
> 
> Défauts constatés et à corriger :
> 
> * Lorsqu'on supprime/cache un module et qu'on relance l'activité Fenetre en question, les modules supprimés redeviennent visibles
> * Crash de la FenetreBoite pour la raison suivante :
> 
> ```shell
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lasalle.domotifications/com.lasalle.domotifications.FenetreBoiteAuxLettres}: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
>  Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
> at com.lasalle.domotifications.FenetreBoiteAuxLettres.initialiserGUI(FenetreBoiteAuxLettres.java:137)
> at com.lasalle.domotifications.FenetreBoiteAuxLettres.onCreate(FenetreBoiteAuxLettres.java:98)
> ```
> 
> * Le code pour ajouter/rendre visible les modules dans la méthode initialiserGUI() ne fonctionne pas
> * Lorsqu'on appuie sur le boutonAjouterModule, seul les modules présents dans la BDD s'affichent



> Sur le dernier commit :
> 
> * Remaniement de BaseDeDonnees.java avec clangformat
> * Ajout de la classe BoiteDeDialogue.java
> * Ajout de la méthode afficherBoiteDialogueSuppression dans les différentes fenêtres
> * Ajout de code dans la méthode initialiserGUI()
> 
> Défauts constatés et à corriger :
> 
> * Lorsqu'on supprime/cache un module et qu'on relance l'activité Fenetre en question, les modules supprimés redeviennent visibles
> * Crash de la FenetreBoite pour la raison suivante :
> 
> ```shell
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lasalle.domotifications/com.lasalle.domotifications.FenetreBoiteAuxLettres}: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
>  Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
> at com.lasalle.domotifications.FenetreBoiteAuxLettres.initialiserGUI(FenetreBoiteAuxLettres.java:137)
> at com.lasalle.domotifications.FenetreBoiteAuxLettres.onCreate(FenetreBoiteAuxLettres.java:98)
> ```
> 
> * Le code pour ajouter/rendre visible les modules dans la méthode initialiserGUI() ne fonctionne pas
> * Lorsqu'on appuie sur le boutonAjouterModule, seul les modules présents dans la BDD s'affichent



> Sur le dernier commit :
> 
> * Remaniement de BaseDeDonnees.java avec clangformat
> * Ajout de la classe BoiteDeDialogue.java
> * Ajout de la méthode afficherBoiteDialogueSuppression dans les différentes fenêtres
> * Ajout de code dans la méthode initialiserGUI()
> 
> Défauts constatés et à corriger :
> 
> * Lorsqu'on supprime/cache un module et qu'on relance l'activité Fenetre en question, les modules supprimés redeviennent visibles
> * Crash de la FenetreBoite pour la raison suivante :
> 
> ```shell
> java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lasalle.domotifications/com.lasalle.domotifications.FenetreBoiteAuxLettres}: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
>  Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
> at com.lasalle.domotifications.FenetreBoiteAuxLettres.initialiserGUI(FenetreBoiteAuxLettres.java:137)
> at com.lasalle.domotifications.FenetreBoiteAuxLettres.onCreate(FenetreBoiteAuxLettres.java:98)
> ```
> 
> * Le code pour ajouter/rendre visible les modules dans la méthode initialiserGUI() ne fonctionne pas
> * Lorsqu'on appuie sur le boutonAjouterModule, seul les modules présents dans la BDD s'affichent

Mes remarques :

- Il n'y a aucun `Log` dans ton code pour t'aider à comprendre le fonctionnement.
- tu devrais réfléchir à ce que tu veux faire quand tu ajoutes un module (avec une feuille et un stylo et pas devant un écran)
- tu devrais réfléchir à ce que tu veux faire quand tu supprimes un module (avec une feuille et un stylo et pas devant un écran)

Ton code pour ajouter/supprimer un module n'a aucun sens. Tu peux tout supprimer et recommencer.

2024-06-06 14:18 UTC, OthmanLatyaoui commented
Code à compléter

J'ai également un peu de mal avec la requête sql pour ajouter le module

2024-06-06 16:17 UTC, OthmanLatyaoui commented
```bash

2024-06-06 18:15:52.016 26700-26700 _BaseDeDonnees          com.lasalle.domotifications          D  insererModule() idModule = 4 idTypesModules = 2 nom = Nouvelle Machine actif = true couleur = #FF0000
2024-06-06 18:15:52.016 26700-26700 _BaseDeDonnees          com.lasalle.domotifications          D  insererModule() requete = INSERT INTO modules (id, nom, idTypesModules, actif, couleur, idDomotifications) VALUES (4, 'Nouvelle Machine', 2, 1, '#FF0000', 1);
2024-06-06 18:15:52.018 26700-26700 _BaseDeDonnees          com.lasalle.domotifications          E  Erreur d'insertion du module
```

La requête SQL s'effectue de ce que j'ai compris mais je ne sais pas pourquoi le module ne s'insère pas

2024-06-07 02:37 UTC, tvaira requested changes

2024-06-07 02:37 UTC, tvaira commented on domotifications-android/Domotifications/app/src/main/java/com/lasalle/domotifications/BaseDeDonnees.java
> +              "DELETE FROM modules WHERE id = " + idModule +
Non, la condition est limitée à la clé qui est `WHERE id = " + idModule + " AND idTypesModules = " + idTypesModules`

2024-06-07 02:37 UTC, tvaira commented on domotifications-android/Domotifications/app/src/main/java/com/lasalle/domotifications/BoiteDeDialogue.java
> +                for(Module module: modules)
Pourquoi veux-tu faire une boucle ? C'est inutile.

2024-06-07 02:41 UTC, tvaira commented on domotifications-android/Domotifications/app/src/main/java/com/lasalle/domotifications/FenetreBoiteAuxLettres.java
> +                // Insérer le module dans la base de données
En réalité, tu ne pourras ajouter un nouveau module seulement si la station lumineuse accepte la demande d'ajout.  Donc normalement, tu dois émettre la requête POST pour faire une demande d'ajout avant d'insérer et instancier le nouveau module.

2024-06-07 02:44 UTC, tvaira commented on domotifications-android/Domotifications/app/src/main/java/com/lasalle/domotifications/FenetreMachine.java
> +        Module nouveauModule = new Module(nbModulesMachines + 1,
`nbModulesMachines` ne correspond pas forcément au dernier `id` de module. Il te faut rechercher un `id` disponible. On peut aussi envisager que ce soit la station qui détermine l'`id` du nouveau module.

2024-06-08 14:50 UTC, tvaira requested changes

2024-06-08 14:50 UTC, tvaira commented on domotifications-android/Domotifications/app/src/main/java/com/lasalle/domotifications/FenetreBoiteAuxLettres.java
>                      if(idModule != -1)
Attention, l'`idModule` n'est pas l'index à utiliser dans le `Vector` ! Il faut faire :

```java
int    numeroModule = getNumeroBoite(idModule);
Module module = modulesBoitesAuxLettres.get(numeroModule); 
```

2024-06-08 14:50 UTC, tvaira commented on domotifications-android/Domotifications/app/src/main/java/com/lasalle/domotifications/FenetreBoiteAuxLettres.java
> +                              ", \"couleur\" \"#00FF00\":, \"actif\": true"
Le `:` est mal placé ! `\"couleur\": \"#00FF00\"`

2024-06-08 14:50 UTC, tvaira commented on domotifications-android/Domotifications/app/src/main/java/com/lasalle/domotifications/FenetreMachine.java
>                      nomAjoutModule = nomModule.getText().toString();
On va ajouter un `trim()` à la fin : `nomAjoutModule = nomModule.getText().toString().trim();`

2024-06-08 14:50 UTC, tvaira commented on domotifications-android/Domotifications/app/src/main/java/com/lasalle/domotifications/FenetrePoubelle.java
> +                int idPoubelle = rechercherIdDisponible();
Attention en mode démo, il te faut tester si l'`id` est supérieur à `0` car sinon cela signifie qu'il n'y a plus d'`id` et cela va faire planter l'application lors de l'accès au `Vector`.

2024-06-08 14:50 UTC, tvaira commented on domotifications-android/Domotifications/app/src/main/res/layout/ajout_module.xml
> +    <ImageView
Tu ne pourras pas le gérer pour l'instant. Tu n'as pas d'événement `onTouch` dans un `AlertDialog`

2024-06-08 21:16 UTC, tvaira approved these changes

2024-06-08 21:19 UTC, merged